(define (make-rat a b)
  (let ((c (gcd a b)))
    (if (= b 0)
        (display "denom can't be zero")
        (if (< (* a b) 0)
              (cons (- (abs (/ a c)))
                    (abs (/ b c)))
              (cons (abs(/ a c))
                    (abs(/ b c)))))))
